CREATE TABLE cdm.dm_courier_ledger (
	id int4 NOT NULL DEFAULT nextval('cdm.dm_payments_to_couriers_id_seq'::regclass),
	courier_id int8 NOT NULL,
	courier_name varchar NOT NULL,
	settlement_year int4 NOT NULL,
	settlement_month int4 NOT NULL,
	orders_count int4 NOT NULL,
	orders_total_sum numeric(14, 2) NOT NULL DEFAULT 0,
	rate_avg numeric NOT NULL,
	order_processing_fee numeric(14, 2) NOT NULL DEFAULT 0,
	courier_order_sum numeric(14, 2) NOT NULL DEFAULT 0,
	courier_tips_sum numeric(14, 2) NOT NULL DEFAULT 0,
	courier_reward_sum numeric(14, 2) NOT NULL DEFAULT 0,
	CONSTRAINT dm_courier_ledger_un UNIQUE (courier_id, courier_name, settlement_year, settlement_month),
	CONSTRAINT dm_payments_to_couriers_check_courier_order_sum CHECK ((courier_order_sum >= (0)::numeric)),
	CONSTRAINT dm_payments_to_couriers_check_courier_reward_sum CHECK ((courier_reward_sum >= (0)::numeric)),
	CONSTRAINT dm_payments_to_couriers_check_courier_tips_sum CHECK ((courier_tips_sum >= (0)::numeric)),
	CONSTRAINT dm_payments_to_couriers_check_order_processing_fee CHECK ((order_processing_fee >= (0)::numeric)),
	CONSTRAINT dm_payments_to_couriers_check_orders_count CHECK ((orders_count >= 0)),
	CONSTRAINT dm_payments_to_couriers_check_orders_total_sum CHECK ((orders_total_sum >= (0)::numeric)),
	CONSTRAINT dm_payments_to_couriers_check_rate_avg CHECK (((rate_avg >= (0)::numeric) AND (rate_avg <= (5)::numeric))),
	CONSTRAINT dm_payments_to_couriers_check_settlement_month CHECK (((settlement_month >= 1) AND (settlement_month <= 12))),
	CONSTRAINT dm_payments_to_couriers_check_settlement_year CHECK (((settlement_year >= 2022) AND (settlement_year <= 2500))),
	CONSTRAINT dm_payments_to_couriers_pk PRIMARY KEY (id)
);